
title: James Goodman Portfolio
logo: /assets/images/logo.png
description: Hello and welcome to my portfolio. This is a collection of projects that I have completed either as part of my degree or as personal projects in my spare time.
theme: jekyll-theme-minimal
