
title: James Goodman Portfolio
logo: /assets/images/logo.png
description: Hello and welcome to my portfolio. Here you can find a collection of projects that I have worked on, ranging from personal projects done in my spare time to those completed  as part of my degree.
theme: jekyll-theme-minimal
